name: redis
services:
  cache:
    image: redis
    ports:
      - "6379:6379"
  backend:
    build: ./backend
    environment:
      - REDIS_NAME=cache
    ports:
      - "3000"
    depends_on:
      - cache
  frontend:
    build: ./frontend
    ports:
      - "3001"
    depends_on:
      - backend